code --install-extension aki77.rails-db-schema
code --install-extension aki77.rails-partial
code --install-extension alexcvzz.vscode-sqlite
code --install-extension aliariff.vscode-erb-beautify
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension bungcip.better-toml
code --install-extension castwide.ruby-debug
code --install-extension castwide.solargraph
code --install-extension codezombiech.gitignore
code --install-extension CraigMaslowski.erb
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension erd0s.terraform-autocomplete
code --install-extension esbenp.prettier-vscode
code --install-extension fabianlauer.vs-code-xml-format
code --install-extension fabiospampinato.vscode-diff
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension HookyQR.beautify
code --install-extension hoovercj.ruby-linter
code --install-extension Hridoy.rails-snippets
code --install-extension ionutvmi.reg
code --install-extension jakebathman.mysql-syntax
code --install-extension kaiwood.endwise
code --install-extension KishoreIthadi.dotnet-core-essentials
code --install-extension KoichiSasada.vscode-rdbg
code --install-extension Kosai106.ruby-syntax-replacer
code --install-extension kraml.vscode-everything-search-and-open
code --install-extension ldrner.rspec-snippets-vscode
code --install-extension litleleprikon.socket-io-vscode
code --install-extension MateuszDrewniak.ruby-test-runner
code --install-extension matthieumu.vscode-rubycommentdoc
code --install-extension miguel-savignano.ruby-symbols
code --install-extension mikestead.dotenv
code --install-extension misogi.ruby-rubocop
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
# Powershell export run => code --list-extensions | % { "code --install-extension $_" }
# Linux export run => code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension nhoizey.gremlins
code --install-extension ninoseki.vscode-gem-lens
code --install-extension pavlitsky.yard
code --install-extension peakchen90.open-html-in-browser
code --install-extension pranaygp.vscode-css-peek
code --install-extension rayhanw.erb-helpers
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension rust-lang.rust-analyzer
code --install-extension samuelcolvin.jinjahtml
code --install-extension serayuzgur.crates
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sianglim.slim
code --install-extension skellock.just
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Swellaby.rust-pack
code --install-extension Swellaby.vscode-rust-test-adapter
code --install-extension vadimcn.vscode-lldb
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wholroyd.jinja
code --install-extension wingrunr21.vscode-ruby
code --install-extension ZneuRay.erb-vscode-snippets
